### ISSUE TITLE
安装问题

### ISSUE THREAD

**Issue by hbwzj** [XiudingCai/MambaTS-pytorch#1]
请问这两个包有没有安装的参考链接。pip install causal-conv1d>=1.2.0
pip install mamba-ssm  。不知道为什么我这边按照您的指示一直报错

**Comment by XiudingCai** [comment]
您好，安装详情可以参考这个链接：[https://github.com/state-spaces/mamba](https://github.com/state-spaces/mamba)，目前Mamba相关的库仅在Linux系统上可以运行，Windows用户可以使用WSL。希望这个可以帮到你！

**Comment by hbwzj** [comment]
> 您好，安装详情可以参考这个链接：https://github.com/state-spaces/mamba，目前Mamba相关的库仅在Linux系统上可以运行，Windows用户可以使用WSL。希望这个可以帮到你！

好的，谢谢您的解答。
